Introduce from_ref_with_range on Parser
NLnetLabs/octseq pull request #43
Opened 2023-10-26 14:29 UTC by DRiKE

This PR introduces a new constructor for `Parser`, similar to the existing `fn from_ref` but taking a range to initialize the parser on a subset of the octets.

It currently errors when the end of the passed range lies beyond the end of the octets, meaning passing in an open-ended range `(n..)` is not possible. Alternatively, we could accept any (open) end and limit it to the length of the octets, and not returning any error.

2023-10-26 15:10 UTC, DRiKE commented
Something like this seems to work. But if we really want to support this it might be cleaner to add `fn from_ref_range_from()` and `fn from_ref_range_to()` taking a RangeFrom / RangeTo, respectively.

```rust
pub fn from_ref_with_range<R>(
    octets: &'a Octs,
    range: R
) -> Result<Self, ShortInput>
where
    Octs: AsRef<[u8]>,
    R: core::ops::RangeBounds<usize>
{
    use std::ops::Bound;
    let octets_len = octets.as_ref().len();

    let pos = match range.start_bound() {
        Bound::Unbounded => 0,
        Bound::Included(n) => {
            if *n - 1 > octets_len {
                octets_len
            } else {
                *n
            }
        }
        Bound::Excluded(_) => unreachable!() // not a thing for the
                                             // start_bound, right?
    };

    let len = match range.end_bound() {
        Bound::Unbounded => octets_len,
        Bound::Excluded(n) => {
            if *n > octets_len {
                octets_len
            } else {
                *n
            }
        }
        Bound::Included(n) => {
            if (n - 1) > octets_len {
                octets_len
            } else {
                n - 1
            }
        }
    };

    let len = if len < pos {
        pos
    } else {
        len
    };

    Ok(
        Parser {
            pos,
            len,
            octets
        }
    )
}
```

2023-10-26 15:25 UTC, partim commented
I’d probably just call the function `with_range`.

2023-10-26 15:27 UTC, partim commented
I wonder if it should just panic if the range is outside the octets’ full range. The use case for the function typically is where you store the range to make a parser on the fly later, so you usually have checked already. And most things that take a range on slices do panic as well, so this may even be consistent.

2023-10-26 17:20 UTC, DRiKE commented
That sounds good, I'll adapt it and rename the fn as well.

2023-10-30 08:40 UTC, DRiKE commented
I guess this happened partly because that's what was there in my vim buffer after a lot of undo-ing, but I also thought it sort of made sense to force to be exact (i.e. an ended `Range` and not a possibly open-ended `RangeBounds`). When you are working with a `Parser` on a stream-like bunch of octets, you might have no idea whether there is stuff before the message you are parsing, or stuff beyond the end of that message. So allowing open-ended ranges sound like a bit of a foot gun?

2023-10-30 13:32 UTC, partim commented
I think there are legitimate use cases for using open ranges. For instance, if you want to split a sequence in two, only remembering the mid point and then use open ranges when creating parsers rather than doing some extra maths to get to the full ranges is probably safer.

So, I think allowing all kinds ranges is probably better.

2023-10-30 21:03 UTC, DRiKE commented
There we go. It does allow ranges such as `2..=1` (equivalent to `2..2` producing a parser with 0 remaining octets), which feel strange to me because such range looks like it is decreasing. But this actually in line with e.g. slice indexing in the standard library.

2023-10-31 14:44 UTC, partim requested changes

2023-10-31 14:45 UTC, partim commented
I think this would benefit from a bunch of tests, especially for the corner cases.

2023-10-31 14:52 UTC, DRiKE commented
Tests, definitely.
With regards to `len`, that always points to what we call the 'end' of the Parser if I'm not mistaking. Should that be renamed?

2023-10-31 14:55 UTC, partim commented
Oh, you are right. Fooled myself there, apparently. Renaming it to `end` is probably a wise move, indeed. (By the looks of it, the code itself tries to avoid using it directly and uses `remaining` instead.)

2023-11-15 15:27 UTC, DRiKE commented on src/parse.rs
> +            Bound::Excluded(_) => unreachable!() // not a thing for the
Apparently, you can specify `RangeBounds` as a tuple, so the start bound can already be exclusive:
```rust
assert_eq!(
    [1,2,3][(Bound::Excluded(0), Bound::Included(2))],
    [1,2,3][1..=2]
);
```

Fixed in the latest commit.

2023-11-15 15:29 UTC, DRiKE commented
Fixes for your comments pushed, unit tests coming up.
And then let's do the renaming of `len` in a separate PR once we're happy with this one.

2023-11-16 10:26 UTC, partim approved these changes

2023-11-16 13:32 UTC, merged